config/routes.rb
# == Route Map
#
#    Prefix Verb  URI Pattern               Controller#Action
#     users GET   /users(.:format)          users#index
#           POST  /users(.:format)          users#create
#  new_user GET   /users/new(.:format)      users#new
# edit_user GET   /users/:id/edit(.:format) users#edit
#      user GET   /users/:id(.:format)      users#show
#           PATCH /users/:id(.:format)      users#update
#           PUT   /users/:id(.:format)      users#update
#     login POST  /login(.:format)          sessions#create
#   session GET   /session(.:format)        sessions#show
#    logout GET   /logout(.:format)         sessions#destroy
#

Rails.application.routes.draw do

  root :to => 'users#index'

  resources :users, :except => :destroy do
    get '/welcome_email',           :action => 'send_welcome_email', :as => 'welcome_email'
  end

  resources :photos, :only => [:create]

  controller :sessions do
    post '/login',          :action => 'create',          :as => 'login'
    get  '/session',        :action => 'show'
    get '/logout',          :action => 'destroy',         :as => 'logout'
  end

  get '/auth/facebook/callback', :to => 'sessions#create'
  get '/auth/facebook',                                   :as => "facebook_login" 
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id          :integer          not null, primary key
#  picture_url :string(255)      not null
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#
# Indexes
#
#  index_photos_on_user_id  (user_id)
#

require 'file_size_validator'

class Photo < ActiveRecord::Base
  belongs_to :user

  mount_uploader :picture_url, PhotoUploader
  validates :picture_url, :presence => true, 
            :file_size => { :maximum => 5.megabytes.to_i }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  nickname        :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  provider        :string(255)      not null
#  uid             :string(255)      not null
#  name            :string(255)      not null
#  first_name      :string(255)
#  last_name       :string(255)
#  image           :string(255)
#  location        :string(255)
#  gender          :string(255)
#  verified        :boolean
#  link            :string(255)
#  avatar          :string(255)
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#


class User < ActiveRecord::Base
  # has_secure_password
  
  validates :email, :presence => true, :uniqueness => true, :length => { :minimum => 6 }, :email => true
  validates :provider, :presence => true
  validates :uid, :presence => true
  validates :name, :presence => true

  has_many :photos

  # validates :password, :presence => true, :length => { :minimum => 6 }, :confirmation => true
  # validates :nickname, :presence => true, :length => { :minimum => 6 }, :uniqueness => true,
  #           :format => { :with => /\A[\w\s]+\z/, message: "nickname cannot contain special characters such as @#$%" }
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.email = auth['info']['email']
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.first_name = auth['info']['first_name']
      user.last_name = auth['info']['last_name']
      user.image = auth['info']['image']
      user.location = auth['info']['location']
      user.gender = auth['extra']['raw_info']['gender']
      user.verified = auth['info']['verified']
      user.link = auth['extra']['raw_info']['link']
    end
  end
end

app/controllers/admins/admins_controller.rb
class Admins::SessionsController < Devise::SessionsController
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  # def create
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil if session[:user_id].blank?

    @current_user ||= User.find_by_id(session[:user_id])
  end

  def login!(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def logout!
    @current_user = nil
    session.clear
  end

  def logged_in?
    current_user.present?
  end

  def redirect_if_logged_in!(url = root_url)
    if logged_in?
      redirect_to(url)
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create

    @photo = current_user.photos.new(photo_params)

    if @photo.save
      redirect_to user_path(current_user), :notice => 'Photo was successfully created.'
    else
      render :new
    end
  end

  def photo_params
    params.require(:photo).permit(:picture_url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create

    p request.env['omniauth.auth']

    auth = request.env['omniauth.auth']
    @user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)

    if @user
      login!(@user)
      redirect_to user_path(@user)
    else
      render redirect_to root_url
    end
    
    # @user = User.find_by_email(session_params[:email])

    # p "I'm receiving Ajax request" if request.xhr?

    # respond_to do |format|
    #   if @user && @user.authenticate(session_params[:password])
    #     login!(@user)
    #     format.json { render :json => @user, :status => :created, :location => @user }
    #     format.html { redirect_to users_path }
    #   else
    #     @error_messages = { :errors => ["Invalid username or password"] }
    #     format.json { render :json => @error_messages, :status => :unprocessable_entity }
    #     puts "I'm sending json format of #{@error_messages} to the browser!"
    #   end
    # end
  end

  def show
  end

  def destroy
    logout! if logged_in?
    
    redirect_to(root_url)
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_authorization!, :only => [:show]

  def index
    if logged_in?
      redirect_to user_path(@current_user)
    else
      render :index
    end
  end

  def show
    @photos = current_user.photos
    render :show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        login!(@user)
        format.json { render :json => @user, :status => :created, :location => @user }
        format.html { redirect_to user_path(@user) }
      else
        format.js   { render :create, :status => :unprocessable_entity }
        format.html { render :new }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def send_welcome_email
    p UserMailer.welcome_email(current_user)
    UserMailer.welcome_email(current_user).deliver
    redirect_to root_path
  end

  private

  def require_authorization!
    redirect_to root_path unless logged_in?
  end

  def user_params
    params.require(:user).permit(:email, :nickname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Signuper</title>
    <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => false %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => false %>
    <%= csrf_meta_tags %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_new_photo_form.html.erb
<%= form_for(:photo, :url => photos_url, :multipart => true) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :picture_url %>
  </div>
  <div class="buttons">
    <%= f.submit 'Create photo' %>
  </div>
<% end %>

app/views/photos/new.html.erb
<%= render partial: "new_photo_form", locals: { :photo => @photo } %>

app/views/shared/_header_all.html.erb
<div id="logged_out_header">
  <nav><%= render :partial => "shared/index_page_modal" %></nav>
</div>
<div class="home_page_notice">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>
</div>

app/views/shared/_index_page_modal.html.erb
<div id="front_page_modal">

  <!-- Button trigger modal -->

  <ul class="modal-button-list">
    <li>
      <%= link_to 'Home', root_url %>
    </li>
    <li>
      <button data-my-modal="#user_modal" data-toggle="modal" class="button_normal">
        Log in
      </button>
    </li>
    <li>
      <button data-my-modal="#sign_up_modal" data-toggle="modal" class="button_normal">
        Sign Up
      </button>
    </li>
  </ul>

   <!-- modal content -->

  <div class="my-modal" id="sign_up_modal">
    <div class="modal-container">
      <div class="my-modal-background"></div>
      <div class="my-modal-content">
        <a href="#" class="my-modal-close">[X]</a>
        <a class="fb_button" href=<%= facebook_login_path %>><i class="fa fa-facebook fa-2x"><span class="text_container">Sign up with Facebook</span></i></a>
      </div>
    </div>
  </div>

  <div class="my-modal" id="user_modal">
    <div class="modal-container">
      <div class="my-modal-background"></div>
      <div class="my-modal-content">
        <a href="#" class="my-modal-close">[X]</a>
        <a class="fb_button" href=<%= facebook_login_path %>><i class="fa fa-facebook fa-2x"><span class="text_container">Log in with Facebook</span></i></a>
        <div id="login_error"></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_login_form.html.erb
<%= form_for(:session, :url => login_path, :method => :post, :remote => true, :html => { :class => "login_form" }, :confirm => 'Are you sure you want to sign in?', :data => { :format => :json }) do |f| %>
  <table class="sign_in_table", cellspacing="20">
    <tr>
      <td align="left"><span class="login_table_content">Email</span></td> 
      <td><%= f.text_field(:email, :placeholder => "Email", :class => "input_box_normal")%></td>
    </tr>
    <tr>
      <td align="left"><span class="login_table_content">Password</span></td>
      <td><%= f.password_field(:password, :placeholder => "Password", :class => "input_box_normal")%></td>
    </tr>
  </table><br>
    <%= f.submit "Login", :class => "button_normal" %>
<% end %>

app/views/users/_sign_up_form.html.erb
<div>
<%= form_for(user, :remote => true, :html => { :class => "sign_up_form", :id => "sign_up_form" }) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><% pluralize(user.errors.count, "error") %>Please check your input for the following guideline</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <h4><%= f.label :email %></h4>
    <%= f.text_field :email, :placeholder => "Email", :class => "input_box_normal" %>
  </div>

  <div class="field">
    <h4><%= f.label :nickname %></h4>
    <%= f.text_field :nickname, :placeholder => "Nickname", :class => "input_box_normal" %>
  </div>

  <div class="field">
    <h4><%= f.label :password  %></h4>
    <%= f.password_field :password, :placeholder => "Password", :class => "input_box_normal" %>
  </div>

  <div class="field">
    <h4><%= f.label :password_confirmation %></h4>
    <%= f.password_field :password_confirmation, :placeholder => "Password", :class => "input_box_normal" %>
  </div>

  <div class="actions">
    <%= f.submit "Create Account", :class => "button_normal" %>
  </div>
<% end %>
</div>

app/views/users/create.js.erb
$('#sign_up_form').replaceWith("<%= j render(:partial => 'sign_up_form', :locals => { :user => @user }) %>");

app/views/users/faceboook_login.html.erb
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '{your-app-id}',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.1' // use version 2.1
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>

app/views/users/index.html.erb
<div id="status">
</div>

<h1>Welcome to Signuper, all we do is Signning you up all day long!</h1>

<%= render :partial => "shared/index_page_modal" %>

app/views/users/new.html.erb
<%= render :partial => "sign_up_form", :locals => { :user => @user } %>

app/views/users/show.html.erb
<div id="status">
</div>

<div class="user_image">
  <img src="<%= current_user.image %>" alt="Siley face">
</div>
<%= link_to 'Logout', logout_path %><br>

<%= link_to 'Send myself welcome email', user_welcome_email_path(current_user) %><br>

<h1>Welcome to Signuper, all we do is Signning you up all day long!</h1>

<h2>wohoo, you have signed up! This is user page</h2>

<h1>photo photo</h1>

<%= render :partial => "photos/new_photo_form", :locals => { :photo => Photo.new } %>

<% if @photos.empty? %>
  <h3>No photos. :(</h3>
<% else %>
  <ul class="photo-list">
    <% @photos.each do |photo| %>
      <li><%= image_tag(photo.picture_url.gallery_fit.url) %></li>
      <li><%= image_tag(photo.picture_url.gallery_fill.url) %></li>
      <li><%= image_tag(photo.picture_url.gallery_limit.url) %></li>
      <li><%= image_tag(photo.picture_url.gallery_pad.url) %></li>
    <% end %>
  </ul>
<% end %>